INSERT INTO LOG (MESSAGE, TYPE, "LEVEL", TIME)
VALUES ('Message1', '1', 'debug', CURRENT_TIMESTAMP);
INSERT INTO LOG (MESSAGE, TYPE, "LEVEL", TIME)
VALUES ('Message2', '2', 'error', CURRENT_TIMESTAMP);
INSERT INTO LOG (MESSAGE, TYPE, "LEVEL", TIME)
VALUES ('Message3', '3', 'warn', CURRENT_TIMESTAMP);